#!/bin/sh

echo "starting.."
HN=$(hostname)
gnome-terminal -t "fileProxy" -x ccnfileproxy /home/theosem/Desktop/sharedFiles/image.orig/ ccnx:/$HN/ &
gnome-terminal -t "startProxy" -x startProxy &
#gnome-terminal -t "monitor" -x monitor /home/theosem/Desktop/search &
ccndstart
#monitor /home/theosem/Desktop/search

